# Generated by Django 5.2 on 2025-08-14 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notebook',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_notebook_name_per_owner'),
        ),
    ]
