# Generated by Django 5.2.4 on 2025-08-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0003_note'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('notebook', 'name'), name='unique_note_per_notebook'),
        ),
    ]
