# Generated by Django 5.2.4 on 2025-08-30 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0004_note_unique_note_per_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='note_taking.notebook'),
        ),
    ]
