# Generated by Django 5.2.4 on 2025-09-01 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0005_alter_note_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(max_length=50)),
                ('block_content', models.JSONField(default=dict)),
                ('block_order', models.IntegerField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='note_taking.note')),
            ],
        ),
    ]
