# Generated by Django 5.2.4 on 2025-09-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0007_alter_block_block_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('note', 'block_order'), name='unique_note_block_order'),
        ),
    ]
