# Generated by Django 5.2.4 on 2025-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0008_block_unique_note_block_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('note', 'order')},
        ),
        migrations.RemoveConstraint(
            model_name='block',
            name='unique_note_block_order',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='block_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='block_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='block_type',
            new_name='type',
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('note', 'order'), name='unique_note_block_order'),
        ),
    ]
