# Generated by Django 5.2.4 on 2025-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0009_alter_block_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('note', 'position')},
        ),
        migrations.RemoveConstraint(
            model_name='block',
            name='unique_note_block_order',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='order',
            new_name='position',
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('note', 'position'), name='unique_note_block_position'),
        ),
    ]
