# Generated by Django 5.2.4 on 2025-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0010_alter_block_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
