# Generated by Django 5.2.4 on 2025-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_taking', '0011_alter_block_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='additional_attributes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
