# Generated by Django 5.2.4 on 2025-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='notebook_color',
            field=models.CharField(default='#b3b3b3', max_length=7),
        ),
    ]
