# Generated by Django 5.2.4 on 2025-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notebook_notebook_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
